Insert into employee(username, password, name, email) values (“bpio”, “11111”, “Bianca”, “bpio@wellesley.edu”)
Insert into shifts(permanent, day, time,employee) values (1, “Monday”, “5:00pm”, "bpio")
Insert into employee(username, password, name, email) values ("wwellesley", “12345”, “Wendy”, “wwellesley@wellesley.edu”)
Insert into employee(username, password, name, email) values ("wwellesley2", “33333”, “Wanda”, “wwellesley2@wellesley.edu”)
Insert into admin(username, password, name, email) values ("steve1", "54213", "Steve", "sjobs@wellesley.edu")
Insert into shifts(permanent, day, time,employee) values (1, “Monday”, “8:00am”, "wwellesley")
